version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: workatolist
      POSTGRES_USER: olisteradmin
      POSTGRES_PASSWORD: olist

  workatolist:
    build: .
    restart: on-failure
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db