# Generated by Django 3.0.4 on 2020-03-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, help_text='Author name', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='Authors of the book', to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveSmallIntegerField(help_text='Book edition'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(help_text='Book name', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(help_text='Year the book was published'),
        ),
    ]
